Debounce transporter input
USEPA/haztrak pull request #729
Opened 2024-06-11 01:15 UTC by sheckathorne

## Description
Debounces the transporter input in the manifest form while also reducing the minimum number of characters from 5 to 2 before results begin populating. Debounce will limit the number of requests made to the server when typing-to-search while the reduction in characters will allow the user to display results earlier.

## Issue ticket number and link

https://github.com/USEPA/haztrak/issues/727

## Checklist

- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings

2024-06-11 20:07 UTC, dpgraham4401 commented
Thanks @sheckathorne!

I know we already discussed this, I'll review this before the end of this week.

2024-06-13 11:43 UTC, dpgraham4401 commented on client/src/hooks/useDebounce/useDebounce.spec.tsx
> +    vi.useFakeTimers(); // Use fake timers
This looks like it was written by AI, which is fine (if it works and isn't doing it in some backwards way), but it doesn't make sense use comments like`// use fake times` to explain a function call called `vi.useFakeTimers()`. same for the rest of the test.

2024-06-13 12:00 UTC, dpgraham4401 commented on client/src/hooks/useDebounce/useDebounce.spec.tsx
> +    vi.useFakeTimers(); // Use fake timers
I appreciate the 100% test coverage!
![image](https://github.com/USEPA/haztrak/assets/43794491/eaa6d861-61d4-4460-98c4-1dffbbc24e8f)

2024-06-13 13:33 UTC, dpgraham4401 commented
I notice that it's still sending a request with an empty epaID when the user moves focus away from the select input, which I believe it was doing before anyways(?)

![image](https://github.com/USEPA/haztrak/assets/43794491/6897d170-06e5-473b-9b03-ebc9194df00a)

We can remove that call by modifying the skip option in the `useSearchRcraSitesQuery`

```typescript
  const { data } = useSearchRcraSitesQuery(
    {
      siteType: handlerType,
      siteId: debouncedInputValue,
    },
    { skip: skip || debouncedInputValue === '' }
  );
```

@sheckathorne, do you have the time to modify the PR to fix this? I would hate to not clear this technical debt while we're already here. If not I can make these changes.

2024-06-13 13:37 UTC, dpgraham4401 requested changes
everything looks good, just some minor edits.

2024-06-14 07:33 UTC, sheckathorne commented
Sorry I missed your comments, I have been traveling. I will make these edits today and also admit that I had some help with writing only the tests :)

2024-06-14 17:29 UTC, dpgraham4401 approved these changes
Awesome Possum!
Appreciate the work @sheckathorne

2024-06-14 17:30 UTC, merged